### PR TITLE
multiple settings files, backspin and sidespin metrics for CSV exporting

### PR DESCRIPTION
**Pull request by wonder99**

### CODE REVIEW

**Comment by wonder99** [comment]
@rowengb Do you think we could push out the next release?  I think people would benefit from it.

**Comment by rowengb** [comment]
Hey there, could you write some instructions in the ReadME/Settings.json to use with Android/SCRCPY? I don't have an android so I can't test/write instructions. After that, I'm more than happy to push a release.

**Comment by wonder99** [comment]
Sure, I'll write those instructions.  I've continued to work on this project, to make it a little more robust, handling error conditions as cleanly as possible.  I'll clean that up and send you another pull request ASAP.  You may not take them verbatim, but I've been testing with them and like them

**Comment by rowengb** [comment]
Awesome, thanks.

**Pull request merged**
